package com.mcmmorpg.impl.npcs;

import org.bukkit.ChatColor;
import org.bukkit.Location;

import com.mcmmorpg.common.character.PlayerCharacter;
import com.mcmmorpg.common.quest.QuestMarker;

public class MasterAlchemist extends StaticHuman {

	private static final int LEVEL = 20;
	private static final String TEXTURE_DATA = "ewogICJ0aW1lc3RhbXAiIDogMTU5MTgyMDE1NzY3NSwKICAicHJvZmlsZUlkIiA6ICIzM2ViZDMyYmIzMzk0YWQ5YWM2NzBjOTZjNTQ5YmE3ZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJEYW5ub0JhbmFubm9YRCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yMTBhMmFmN2IzOTk0MDZjNTRiNzE1NGRkNzBjZjljOTljZDgxYjg4MTA5YTg0ZGRjN2YwMGY3MzIwMTdkMmYzIgogICAgfQogIH0KfQ==";
	private static final String TEXTURE_SIGNATURE = "puGFxU8lQZpJnSE8SK5A1pwHvmvZdiDYAmdYpxZk6mc3larVX3PjqGWH+Of8uHYyHKRPfJ4bef93QR1Hy1yEhHD3Qtr9tnUEG3DbxLUbIksg+Qr8Ra82EM0KCXqs2MLy8aCbbXk55kz5JpEqEgfkMqvGJZuGAtwyqAzTkdGWhDEN8Fopw30IAG6CyQ/5BuFZuascY9U9Wtboi6hnxE5kU3lyhDO3o4Sx6nH0FnZhsiLGxX5Z7erGNz9rclsBmOQYc30WMX8AcHYCSQIOzIxCT2cFxce8IppLy9gQ8bwZYBjIJqrp4RU6gpC1hxobaSJaJ4XQTGfH152mLwsWGC/MITp8QGktFo2Z3S7DLZ++RI18JMg23UY+Ah98+JiicpWJDfA/MTjc8iT4Mxj6EUGZxO8CCwM4ZzidsW+BHTgN+z+6DPbom2nbGk1lb5qiKV++byBWux0d7RbZtTfZ7e+mEMNvmGjSuuqYmTg20AZ1HNt8P1Ga+KkXnlgho5qgADiDmf+M4TkkriiKRlz1zfYR7ROAPhvbaZk2/X8cIfCXIK4o/Jpl5vRkbjidB8NgSAm50WK3GzMSvUEjQHI6A1r1vMkWSBaIMgJ+V1rMpLS/m0M9fBunxt8BG9uGFk0aoY/udNoTbLQgeuDaWI/lhOOWEOgzqIIHXPdS/CPaiH78bXc=";

	public MasterAlchemist(Location location) {
		super(ChatColor.GREEN + "Master Alchemist", LEVEL, location, TEXTURE_DATA, TEXTURE_SIGNATURE);
		QuestMarker.createMarker(location.clone().add(0, 2.25, 0));
	}

	@Override
	protected void onInteract(PlayerCharacter pc) {

	}

}
